#+TITLE:i3 configuration file
#+PROPERTY: header-args :tangle config

Only because I like the tabbed mode a lot.

i3 is a [[https://en.wikipedia.org/wiki/Tiling_window_manager][tiling window manager]], targeted towards advanced users and developers. Check [[https://i3wm.org/][i3's website]] for more info and full documentation.

This configuration was made for the i3-gaps fork, but you can still use it in normal i3 by removing the first 3 lines. It uses the tabbed mode by default and IJKL to move around, based on my Emacs configuration which uses those bindings.

* Installation
Clone the git repository and move the files to the ~/.config/i3 directory.

* Explaining the configuration

** Basic stuff
The first 3 lines set the sizes of the window borders and gaps.
The super key (windows key) is set as the modifier key and the floating modifier.
Your default monospace font will be used as the font in i3 and the default mode will be the tabbed mode.

#+BEGIN_SRC ~/.config/i3/config
for_window [class="^.*"] border pixel 2 
gaps inner 5 
gaps outer 5

set $mod Mod4
floating_modifier $mod

font pango:monospace 8
workspace_layout tabbed
#+END_SRC

** Program bindings
Volume keys are set to adjust the volume using pactl.
- /Super + Enter/ starts a terminal by using the /i3-sensible-terminal/ command
- /Super + Shift + q/ kills the current active window

Rofi is used as the application launcher and some more stuff, make sure that the used /modi/ are set up in your rofi configuration.
- /Super + D/ to run programs (similar to dmenu)
- /Super + W/ to change windows
- /Super + R/ to browse files

#+BEGIN_SRC ~/.config/i3/config
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle

bindsym $mod+Return exec i3-sensible-terminal

bindsym $mod+Shift+q kill

bindsym $mod+d exec --no-startup-id rofi -show run # run programs
bindsym $mod+w exec --no-startup-id rofi -show window -show-icons
bindsym $mod+r exec --no-startup-id rofi -show file-browser -show-icons
#+END_SRC

** Window management
Key bindings to manage your windows. Bindings that use IJKL can also use the arrow keys.
- /Super + IJKL/ changes the focused window
- /Super + Shift + IJKL/ moves the focused window.
- /Super + H/ makes horizontal splits when opening a new window in split mode
- /Super + V/ vertical splits in tiling mode
- /Super + F/ toggles fullscreen mode for the focused window
- /Super + Space/ changes the focus between tiled and floating windows
- /Super + S/ changes to stacking mode
- /Super + T/ changes to tabbed mode (default)
- /Super + E/ changes to split mode
- /Super + Alt + IJKL/ resizes windows

#+BEGIN_SRC ~/.config/i3/config
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+i focus up
bindsym $mod+l focus right
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+i move up
bindsym $mod+Shift+l move right
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

bindsym $mod+h split h
bindsym $mod+v split v
bindsym $mod+f fullscreen toggle

bindsym $mod+s layout stacking
bindsym $mod+t layout tabbed
bindsym $mod+e layout toggle split

bindsym $mod+Shift+space floating toggle
bindsym $mod+space focus mode_toggle

bindsym $mod+Mod1+j resize shrink width 10 px or 10 ppt
bindsym $mod+Mod1+k resize grow height 10 px or 10 ppt
bindsym $mod+Mod1+i resize shrink height 10 px or 10 ppt
bindsym $mod+Mod1+l resize grow width 10 px or 10 ppt
bindsym $mod+Mod1+Left resize shrink width 10 px or 10 ppt
bindsym $mod+Mod1+Down resize grow height 10 px or 10 ppt
bindsym $mod+Mod1+Up resize shrink height 10 px or 10 ppt
bindsym $mod+Mod1+Right resize grow width 10 px or 10 ppt
#+END_SRC

** Workspaces and bindings
The workspaces and their names are defined. Emacs is assigned to workspace 1 and Discord is assigned to workspace 4.
- /Super + 1-4/ to move from workspaces 1 to 4
- /Super + Shift + 1-4/ to send the current window to a workspace

#+BEGIN_SRC ~/.config/i3/config
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"

bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4

bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4

assign [class="Emacs"] 1
assign [class="discord"] 4
#+END_SRC

** Reloading and quitting i3
- /Super + Shift + C/ to reload the configuration file
- /Super + Shift + R/ to restart i3 (your session isn't affected)
- /Super + Shift + E/ to exit i3, it will give you a warning before quitting

#+BEGIN_SRC ~/.config/i3/config
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'Exit i3?' -B 'Yes, exit i3' 'i3-msg exit'"
#+END_SRC

** Bar
Make the bar appear on the top and use i3blocks as the bar.

#+BEGIN_SRC ~/.config/i3/config
bar {
	position top
        status_command i3blocks
}
#+END_SRC

** Autostart
Some programs will be started along with i3. A script is included that sets some keyboard settings (keyboard layout and speed) and sets a wallpaper using /nitrogen/.

#+BEGIN_SRC ~/.config/i3/config
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork
exec --no-startup-id compton -b
exec --no-startup-id nm-applet
exec --no-startup-id emacs
exec --no-startup-id i3-sensible-terminal
exec --no-startup-id discord

exec --no-startup-id $HOME/.config/i3/autostart
#+END_SRC
